apiVersion: v1
kind: Service
metadata:
  name: service-test
  labels:
    app: nestjs-example
spec:
  selector:
    app: nestjs-example
  type: NodePort
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 3000